{"timestamp":"2025-05-10T02:05:01.855020","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-10T02:05:01.856128","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-10T02:05:01.937802","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-05-10T02:05:02.030840Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-10T02:05:02.031668Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-10T02:05:02.032214Z","level":"info","event":"Current task name:run_full_etl","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-10T02:05:02.033202Z","level":"info","event":"Dag name:etl_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-10T02:05:02.031533","level":"info","event":"Connection Retrieved 'postgres_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-05-10T02:05:02.038073","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"postgres\" (172.21.0.2), port 5432 failed: FATAL:  password authentication failed for user \"admin\"\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/etl_pipeline.py","lineno":33,"name":"run_full_etl"},{"filename":"/opt/airflow/dags/etl_dim_date.py","lineno":7,"name":"extract_dates"},{"filename":"/opt/airflow/dags/db_connections.py","lineno":7,"name":"get_pg_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}]}]}
{"timestamp":"2025-05-10T02:05:02.138584Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-10T02:05:02.139778Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-10T02:05:02.140747Z","level":"info","event":"Task:<Task(PythonOperator): run_full_etl>","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-10T02:05:02.141354Z","level":"info","event":"Failure caused by connection to server at \"postgres\" (172.21.0.2), port 5432 failed: FATAL:  password authentication failed for user \"admin\"","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-10T02:05:02.141787Z","level":"info","event":"","chan":"stdout","logger":"task"}
